
export const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORIES: '[CATEGORY] SET_CATEGORIES',
  FETCH_CATEGORIES_START: '[CATEGORY] FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: '[CATEGORY] FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: '[CATEGORY] FETCH_CATEGORIES_FAILED',
};