
export enum CATEGORIES_ACTION_TYPES {
  FETCH_CATEGORIES_START = '[CATEGORY] FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS = '[CATEGORY] FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED = '[CATEGORY] FETCH_CATEGORIES_FAILED',
};